AWSTemplateFormatVersion: '2010-09-09'
Description: Day4 Serverless Stack for AWS Academy Learner Lab (S3 Website Hosting)

Parameters:
  LabRoleArn:
    Type: String
    Description: ARN of the LabRole
  LambdaCodeBucket:
    Type: String
    Description: S3 bucket containing api-academy.zip

Resources:
  EmployeeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: day4-employees
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: day4-files
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'day4-files-${AWS::AccountId}'
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedHeaders:
              - '*'
            ExposedHeaders:
              - ETag
            MaxAge: 3000

  ApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: day4-api
      Runtime: nodejs22.x
      Handler: index.handler
      MemorySize: 512
      Timeout: 30
      Role: !Ref LabRoleArn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: api-academy.zip
      Environment:
        Variables:
          EMPLOYEE_TABLE_NAME: !Ref EmployeeTable
          FILES_TABLE_NAME: !Ref FilesTable
          FILES_BUCKET_NAME: !Ref FilesBucket

  ApiFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref ApiFunction
      Cors:
        AllowOrigins:
          - '*'
        AllowMethods:
          - '*'
        AllowHeaders:
          - '*'

  ApiFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiFunction
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'day4-website-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${WebsiteBucket.Arn}/*'

Outputs:
  FunctionUrl:
    Description: Lambda Function URL (API endpoint)
    Value: !GetAtt ApiFunctionUrl.FunctionUrl
  WebsiteUrl:
    Description: S3 Website URL (Frontend)
    Value: !GetAtt WebsiteBucket.WebsiteURL
  WebsiteBucketName:
    Description: S3 Website Bucket Name (for frontend upload)
    Value: !Ref WebsiteBucket
  EmployeeTableName:
    Value: !Ref EmployeeTable
  FilesTableName:
    Value: !Ref FilesTable
  FilesBucketName:
    Value: !Ref FilesBucket
