AWSTemplateFormatVersion: '2010-09-09'
Description: Day4 Serverless Stack for AWS Academy (Lambda Function URL + CloudFront)

Parameters:
  LabRoleArn:
    Type: String
    Description: ARN of the LabRole
  LambdaCodeBucket:
    Type: String
    Description: S3 bucket containing api-academy.zip

Resources:
  # DynamoDB Tables
  EmployeeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: day4-employees
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: day4-files
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # S3 Bucket for file uploads
  FilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'day4-files-${AWS::AccountId}'

  # Lambda Function with Function URL (replaces API Gateway)
  ApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: day4-api
      Runtime: nodejs22.x
      Handler: index.handler
      MemorySize: 512
      Timeout: 30
      Role: !Ref LabRoleArn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: api-academy.zip
      Environment:
        Variables:
          EMPLOYEE_TABLE_NAME: !Ref EmployeeTable
          FILES_TABLE_NAME: !Ref FilesTable
          FILES_BUCKET_NAME: !Ref FilesBucket

  ApiFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref ApiFunction
      Cors:
        AllowOrigins:
          - '*'
        AllowMethods:
          - '*'
        AllowHeaders:
          - '*'

  ApiFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiFunction
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

  # S3 Bucket for static website (frontend)
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: s3:GetObject
            Principal:
              Service: cloudfront.amazonaws.com
            Resource: !Sub '${WebsiteBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${Distribution}'

  # CloudFront Distribution
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub 'day4-oac-${AWS::StackName}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Day 4 CloudFront Distribution for AWS Academy
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ''

Outputs:
  FunctionUrl:
    Description: Lambda Function URL (API endpoint)
    Value: !GetAtt ApiFunctionUrl.FunctionUrl
  CloudFrontUrl:
    Description: CloudFront Distribution URL (Frontend)
    Value: !Sub 'https://${Distribution.DomainName}'
  WebsiteBucketName:
    Description: S3 Website Bucket Name (for frontend upload)
    Value: !Ref WebsiteBucket
  EmployeeTableName:
    Value: !Ref EmployeeTable
  FilesTableName:
    Value: !Ref FilesTable
  FilesBucketName:
    Value: !Ref FilesBucket
